(global-set-key "\C-x\C-b" 'buffer-menu)
(global-set-key [C-tab] 'other-window) ; vimy window switching
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-g" 'gist-buffer)
(global-set-key (kbd "A-M-]") 'align)
(global-set-key (kbd "A-]") 'indent-region)
(global-set-key "\C-xg" 'magit-status)
(global-set-key "\M-i" 'insert-soft-tab)
(global-set-key "\C-x\C-i" 'ido-goto-symbol)
(global-set-key "\C-xp" 'defunkt-find-config)
(global-set-key [remap kill-word] 'defunkt-kill-word)
(global-set-key [remap backward-kill-word] 'defunkt-backward-kill-word)
(global-set-key [remap aquamacs-backward-kill-word] 'defunkt-backward-kill-word)
(global-set-key [A-return] 'insert-blank-line-after-current)
(global-set-key [C-return] 'defunkt-duplicate-line)
(global-set-key [M-up] 'defunkt-inc-num-at-point)
(global-set-key [M-down] 'defunkt-dec-num-at-point)
(global-set-key (kbd "C-*") 'isearch-forward-at-point)